name: qsw-collector

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch: {}

# No overlaps — if a run is still going, the next queues
concurrency:
  group: qsw-collector
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install boto3 pandas matplotlib scikit-learn

      - name: Run one collection pass
        env:
          # Experiment params
          QSW_TRIALS: "600"
          QSW_PHASE_LEN: "8"
          QSW_MAX_STEPS: "30"
          QSW_BATCH: "256"
          QSW_MAX_RETRIES: "12"
          QSW_BACKOFF: "2.0"

          # Pure QRNG + providers
          QSW_PURE: "1"
          QSW_QRNG_PROVIDERS: "anu"
          QSW_PURE_MAX_WAIT: "1500"   # ~25 min cap on CI; 0 = infinite
          QSW_CONDITIONS: "quantum"

          # R2 creds
          S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
          S3_REGION: "auto"
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_PREFIX: ${{ secrets.S3_PREFIX }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: python actions_runner.py

      - name: Summary
        if: always()
        run: |
          echo "### Quantum Signal Walker — Latest Run" >> $GITHUB_STEP_SUMMARY
          python - <<'PY' >> $GITHUB_STEP_SUMMARY
          import pathlib, pandas as pd
          latest = sorted(pathlib.Path("QSW_runs").glob("*_v2.7_actions_*"))[-1]
          df = pd.read_csv(latest/"results_summary.csv")
          qr = None
          try: qr = float(df.loc[df["condition"]=="quantum","quantum_ratio"].fillna(0).values[0])
          except Exception: pass
          print(f"Run: {latest.name}  \nFiles: {sum(1 for _ in latest.rglob('*') if _.is_file())}  \nQuantum ratio: {qr}")
          PY
